# Generated by Django 5.0.2 on 2024-03-22 10:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='task name')),
                ('slug', models.CharField(max_length=127, unique=True)),
                ('code_task', models.TextField()),
                ('solution', models.TextField()),
                ('hint', models.CharField(max_length=511)),
                ('func_input', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ('func_output', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ('key_words', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='vulnerability name')),
                ('slug', models.CharField(max_length=127, unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
