# Generated by Django 5.0.2 on 2024-04-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0004_solvedtask_task_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='func_input',
        ),
        migrations.RemoveField(
            model_name='task',
            name='func_output',
        ),
        migrations.RemoveField(
            model_name='task',
            name='key_words',
        ),
        migrations.AddField(
            model_name='task',
            name='gpt_question',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
