# Generated by Django 5.0.2 on 2024-04-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0005_remove_task_func_input_remove_task_func_output_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hint',
            field=models.TextField(),
        ),
    ]
