# Generated by Django 5.0.2 on 2024-04-17 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0006_alter_task_hint'),
    ]

    operations = [
        migrations.CreateModel(
            name='GptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField()),
                ('answer', models.TextField(max_length=127)),
                ('negative', models.BooleanField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.task')),
            ],
        ),
    ]
