# Generated by Django 5.0.2 on 2024-04-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0007_gptquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gptquestion',
            name='task',
        ),
        migrations.AddField(
            model_name='gptquestion',
            name='task',
            field=models.ManyToManyField(to='coding.task'),
        ),
    ]
