# Generated by Django 5.0.2 on 2024-04-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0008_remove_gptquestion_task_gptquestion_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptquestion',
            name='answer',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='gptquestion',
            name='question',
            field=models.TextField(),
        ),
    ]
