# Generated by Django 5.0.2 on 2024-04-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0009_alter_gptquestion_answer_alter_gptquestion_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptquestion',
            name='compare_code',
            field=models.BooleanField(default=False),
        ),
    ]
