# Generated by Django 5.0.2 on 2024-04-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0011_remove_gptquestion_task_task_gpt_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='gpt_question',
        ),
    ]
