# Generated by Django 5.0.2 on 2024-04-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0012_remove_task_gpt_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gptquestion',
            name='negative',
        ),
        migrations.AddField(
            model_name='gptquestion',
            name='order',
            field=models.IntegerField(default=100),
        ),
    ]
