# Generated by Django 5.0.2 on 2024-04-22 16:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0014_alter_gptquestion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='key_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=511), default=list, size=None),
        ),
    ]
