# Generated by Django 5.0.2 on 2024-04-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0015_task_key_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='gpt_questions',
            field=models.ManyToManyField(blank=True, to='coding.gptquestion'),
        ),
    ]
