# Generated by Django 5.0.2 on 2024-04-24 09:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0017_rename_compare_code_gptquestion_long_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='key_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=511), default=list, size=None),
        ),
    ]
