# Generated by Django 5.0.2 on 2024-04-24 09:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0018_alter_task_key_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='key_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=511), default=list, size=None),
        ),
    ]
