version: "3.9"
services:
  secure_coder:
    depends_on:
      - db
    build: .
    image: secure_coder
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: secure_coder_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    # volumes:
    #   - ./postgres_data:/var/lib/postgresql/data
